CREATE OR REPLACE VIEW financial_analysis_clean AS
SELECT fs.security_id,
    s.ticker,
    fs.period_type,
    fs.period_end,
    fs.fiscal_year,
    fs.fiscal_quarter,
    fs.filed_date,
    fs.revenue,
    fs.gross_profit,
    fs.operating_income,
    fs.net_income,
    fs.eps_basic,
    fs.eps_diluted,
    fs.total_assets,
    fs.total_liabilities,
    fs.total_equity,
    fs.cash_and_equivalents,
    fs.operating_cash_flow,
    fs.capital_expenditures,
    fs.free_cash_flow,
    fm.revenue_growth AS revenue_growth_pct,
    fm.revenue_yoy_growth AS revenue_yoy_pct,
    fm.net_income_growth AS net_income_growth_pct,
    fm.net_income_yoy_growth AS net_income_yoy_pct,
    fm.gross_margin AS gross_margin_pct,
    fm.operating_margin AS operating_margin_pct,
    fm.net_margin AS net_margin_pct,
    fm.fcf_margin AS fcf_margin_pct,
    fm.operating_cash_flow_margin AS operating_cash_flow_margin_pct,
    fm.fcf_growth AS fcf_growth_pct,
    fm.fcf_yoy_growth AS fcf_yoy_growth_pct,
    fm.capex_revenue_ratio AS capex_revenue_ratio_pct,
    fs.source,
    fm.calculated_at
   FROM financial_statements fs
     JOIN securities s ON s.id = fs.security_id
     LEFT JOIN financial_metrics fm ON fm.financial_statement_id = fs.id AND fm.security_id = fs.security_id AND fm.period_type = fs.period_type AND fm.period_end = fs.period_end;
