CREATE OR REPLACE VIEW financial_health_snapshot AS
WITH quarterly_metrics AS (
         SELECT financial_analysis_clean.security_id,
            financial_analysis_clean.ticker,
            financial_analysis_clean.period_type,
            financial_analysis_clean.period_end,
            financial_analysis_clean.fiscal_year,
            financial_analysis_clean.fiscal_quarter,
            financial_analysis_clean.filed_date,
            financial_analysis_clean.revenue,
            financial_analysis_clean.gross_profit,
            financial_analysis_clean.operating_income,
            financial_analysis_clean.net_income,
            financial_analysis_clean.eps_basic,
            financial_analysis_clean.eps_diluted,
            financial_analysis_clean.total_assets,
            financial_analysis_clean.total_liabilities,
            financial_analysis_clean.total_equity,
            financial_analysis_clean.cash_and_equivalents,
            financial_analysis_clean.operating_cash_flow,
            financial_analysis_clean.capital_expenditures,
            financial_analysis_clean.free_cash_flow,
            financial_analysis_clean.revenue_growth_pct,
            financial_analysis_clean.revenue_yoy_pct,
            financial_analysis_clean.net_income_growth_pct,
            financial_analysis_clean.net_income_yoy_pct,
            financial_analysis_clean.gross_margin_pct,
            financial_analysis_clean.operating_margin_pct,
            financial_analysis_clean.net_margin_pct,
            financial_analysis_clean.fcf_margin_pct,
            financial_analysis_clean.operating_cash_flow_margin_pct,
            financial_analysis_clean.fcf_growth_pct,
            financial_analysis_clean.fcf_yoy_growth_pct,
            financial_analysis_clean.capex_revenue_ratio_pct,
            financial_analysis_clean.source,
            financial_analysis_clean.calculated_at,
            lag(financial_analysis_clean.revenue_yoy_pct) OVER (PARTITION BY financial_analysis_clean.security_id ORDER BY financial_analysis_clean.period_end) AS previous_revenue_yoy_pct,
            lag(financial_analysis_clean.gross_margin_pct) OVER (PARTITION BY financial_analysis_clean.security_id ORDER BY financial_analysis_clean.period_end) AS previous_gross_margin_pct,
            lag(financial_analysis_clean.operating_margin_pct) OVER (PARTITION BY financial_analysis_clean.security_id ORDER BY financial_analysis_clean.period_end) AS previous_operating_margin_pct,
            lag(financial_analysis_clean.net_margin_pct) OVER (PARTITION BY financial_analysis_clean.security_id ORDER BY financial_analysis_clean.period_end) AS previous_net_margin_pct,
            lag(financial_analysis_clean.fcf_margin_pct) OVER (PARTITION BY financial_analysis_clean.security_id ORDER BY financial_analysis_clean.period_end) AS previous_fcf_margin_pct,
            lag(financial_analysis_clean.capex_revenue_ratio_pct) OVER (PARTITION BY financial_analysis_clean.security_id ORDER BY financial_analysis_clean.period_end) AS previous_capex_revenue_ratio_pct
           FROM financial_analysis_clean
          WHERE financial_analysis_clean.period_type = 'quarterly'::text
        )
 SELECT security_id,
    ticker,
    period_end,
    fiscal_year,
    fiscal_quarter,
    revenue,
    net_income,
    free_cash_flow,
    revenue_yoy_pct,
    gross_margin_pct,
    operating_margin_pct,
    net_margin_pct,
    fcf_margin_pct,
    fcf_yoy_growth_pct,
    capex_revenue_ratio_pct,
    revenue_yoy_pct - previous_revenue_yoy_pct AS revenue_growth_change,
    gross_margin_pct - previous_gross_margin_pct AS gross_margin_change,
    operating_margin_pct - previous_operating_margin_pct AS operating_margin_change,
    net_margin_pct - previous_net_margin_pct AS net_margin_change,
    fcf_margin_pct - previous_fcf_margin_pct AS fcf_margin_change,
    capex_revenue_ratio_pct - previous_capex_revenue_ratio_pct AS capex_intensity_change
   FROM quarterly_metrics;
